name: DeploySUSHIBI
on:
  release:
      types: [created]
      
jobs:
  merge-pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
  QAS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy to QA environment
        run: |
          echo "Building and deploying to QA environment..."
          
  PRD:
    needs: QAS
    runs-on: ubuntu-latest
   
    if: steps.approval.outputs.approved == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy to QA environment
        run: |
          echo "Building and deploying to Production environment..."


      
